###############################################################################
#
#   Software to be installed in the main environment
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

  name: demon-runner

  channels:
    - bioconda
    - conda-forge

  dependencies:
    - boost-cpp=1.77.0
    - compilers=1.3.0
    - graphviz=2.50.0
    - jinja2=3.0.3
    - python=3.10.2
    - pyyaml=6.0
    - snakemake=6.15.5

...
