###############################################################################
#
#   Config options for the snakemake workflow
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

### WORKFLOW PARAMETERS ###

# Path to the cloned repository
# (absolute path is required)
workflow_repo_path: "/Users/maciek/demon-runner"
#workflow_repo_path: "/home/runner/work/demon-runner/demon-runner"

# Path for the output directory
# (absolute path is required)
workflow_analysis_outdir: "/Users/maciek/demon-runner/output"
#workflow_analysis_outdir: "/home/runner/work/demon-runner/demon-runner"

### DEMON PARAMETERS ###

# spatial_structure
log2_deme_carrying_capacity: [9, 10]

# dispersal
migration_type: 0
init_migration_rate: "2e-03"
migration_edge_only: 1
migration_rate_scales_with_K: 1

# mutation_rates
mu_driver_birth: "1e-05"
mu_passenger: 0.1
mu_driver_migration: 0
passenger_pop_threshold: -1
  
# fitness_effects
normal_birth_rate: 0.9
baseline_death_rate: 0
s_driver_birth: 0.1
s_passenger: 0
s_driver_migration: 0
max_relative_birth_rate: 10
max_relative_migration_rate: 10

# non_biological_parameters
init_pop: 1
matrix_max: -1
max_pop: 1000000
max_time: 86400
max_generations: 200
seed: 10
write_grid: 0
write_clones_file: 0
write_demes_file: 0
record_matrix: 0
write_phylo: 0
calculate_total_diversity: 0
biopsy_size_per_sample: 100

...
