###############################################################################
#
#   Config options for the snakemake workflow
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

### WORKFLOW PARAMETERS ###

# Path to the cloned repository
# (absolute path is required)
#workflow_repo_path: "/Users/maciek/demon-runner"
workflow_repo_path: "/home/runner/work/demon-runner/demon-runner"

# Path for the output directory
# (absolute path is required)
#workflow_analysis_outdir: "/Users/maciek/demon-runner/output"
workflow_analysis_outdir: "/home/runner/work/demon-runner/demon-runner"

### DEMON PARAMETERS ###

demon_param1: [1,2]

demon_param2: "abc"

...
