###############################################################################
#
#   Config options for the snakemake workflow
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

# Path for the output directory
# (absolute path is required)
outdir: "."

...
