###############################################################################
#
#   Snakemake profile for a local workflow execution
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---
snakefile: "workflow/Snakefile"
cores: 1
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: conda
keep-going: true
verbose: true

...
